In [10]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [5]:
_beta = np.array([9, 1, 1, 1, 1])

def get_data():
    global _beta
    np.random.seed(1234)
    num_train, num_valid = 5, 2
    n = num_train + num_valid
    X = np.zeros((n, 5))
    X[:, 0] = 1
    X[:, 1] = X[:, 0] + np.random.randn(n)
    for i in range(2, 5):
        X[:, i] = X[:, i - 1] + np.random.randn(n) * 0.01
    y = np.dot(X, _beta) + np.random.randn(n)
    return X[:num_train, :], y[:num_train], X[num_train:, :], y[num_train:]

In [6]:
train_X, train_y, valid_X, valid_y = get_data()

In [7]:
train_X

array([[ 1.        ,  1.47143516,  1.46506993,  1.46172916,  1.45516946],
       [ 1.        , -0.19097569, -0.19081873, -0.19079755, -0.18886333],
       [ 1.        ,  2.43270697,  2.41028012,  2.41433465,  2.41986904],
       [ 1.        ,  0.6873481 ,  0.69884846,  0.70173938,  0.7149209 ],
       [ 1.        ,  0.27941127,  0.28933073,  0.30254231,  0.29784926]])

In [8]:
train_y

array([14.67029517,  9.29751388, 18.27935055, 12.1402945 , 11.21671213])

In [13]:
linear_regression = LinearRegression()
linear_regression.fit(train_X, train_y)
train_y_predictions = linear_regression.predict(train_X)
beta = linear_regression.coef_

In [16]:
M = np.matmul(train_X, beta)
M

array([ 4.74885538, -0.62392591,  8.35791076,  2.2188547 ,  1.29527234])

In [17]:
beta

array([  0.        ,  15.07525496, -49.76535163,  37.79626436,
         0.15696709])

In [21]:
a = np.array([[1,2,3],
            [4,5,6]])
b = np.array([1, 2, 1])
c = np.matmul(a, b)
c

array([ 8, 20])

In [22]:
c

array([ 8, 20])

In [26]:
y = np.array([1, 2])
d = (c - y)**2

In [27]:
d

array([ 49, 324])

In [29]:
d.sum()

373