In [162]:
import os.path
import math
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.artist import setp
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [163]:
dataset = np.loadtxt("oxford_temperatures.txt")

max_temp = np.array(dataset[:,2])
rain = np.array(dataset[:,5])

max_temp_train, max_temp_test, rain_train, rain_test = train_test_split(max_temp, rain, test_size=0.30, random_state=42)
max_temp_val, max_temp_test, rain_val, rain_test = train_test_split(max_temp_test, rain_test, test_size=0.50, random_state=42)

width_bin = 0.5
max_val = np.max(max_temp)
grid = np.arange(0, max_val + 1,width_bin)

# for a in np.arange(4, 25, 4):
#     split_and_plot(a, max_temp_train, rain_train, max_temp_val, rain_val)

In [164]:
print(max_temp_train.shape, rain_train.shape, max_temp_val.shape, rain_val.shape)

(1360,) (1360,) (292,) (292,)


In [168]:
max_temp_train_less_a = max_temp_train[np.where(max_temp_train < a)].reshape(-1, 1)
n_sample_set_less_a = max_temp_train_less_a.shape[0]
rain_train_less_a = rain_train[np.where(max_temp_train < a)]
max_temp_train_greater_a = max_temp_train[np.where(max_temp_train >= a)].reshape(-1, 1)
n_sample_greater_a = max_temp_train_less_a.shape[0]
rain_train_greater_a = rain_train[np.where(max_temp_train >= a)]
max_temp_val_less_a = max_temp_val[np.where(max_temp_val < a)].reshape(-1, 1)
rain_val_less_a = rain_val[np.where(max_temp_val < a)]
max_temp_val_greater_a = max_temp_val[np.where(max_temp_val >= a)].reshape(-1, 1)
rain_val_greater_a = rain_val[np.where(max_temp_val >= a)].reshape(-1, 1)

In [169]:
print(max_temp_train_less_a.shape, max_temp_greater_a.shape, max_temp_val_less_a.shape, max_temp_val_greater_a.shape)

(32, 1) (1328,) (3, 1) (289, 1)


In [170]:
less_a_weights = np.array(1./n_sample_set_less_a)

In [171]:
less_a_weights = np.repeat(less_a_weights, rain_train_less_a.shape[0])

In [173]:
less_a_weights

array([0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
       0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
       0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
       0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125, 0.03125,
       0.03125, 0.03125, 0.03125, 0.03125])

In [150]:
y_true = np.array([0.5, 1, 2])
#y_true = np.array([[0.5, 1],[-1, 1],[7, -6]])

In [151]:
y_pred = np.array([0, 2, 4])
#y_pred = np.array([[0, 2],[-1, 2],[8, -5]])

In [174]:
sample_weight= np.array([0.5, 0.5, 0.2])

In [175]:
 mean_squared_error(y_true, y_pred, sample_weight=sample_weight)

1.1875

In [154]:
sample_weight= np.array([0.5, 0.5, 0.2])

In [155]:
output_errors = np.average((y_true - y_pred) ** 2, axis=0, weights=sample_weight)

In [156]:
output_errors

1.1875

In [158]:
#mse = np.average(output_errors, weights=sample_weight)

In [145]:
mse

0.625

In [146]:
y_true

array([0.5, 1. ])

In [161]:
((0.5)**2 * 0.5 + 0.5 + 4 * 0.2) /(1.2)

1.1875

In [177]:
y_true.shape)

tuple

In [178]:
np.hstack((y_true, y_pred))

array([0.5, 1. , 2. , 0. , 2. , 4. ])