In [2]:
import os.path
import math
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.artist import setp
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.linear_model import LinearRegression

In [75]:
dataset = np.loadtxt("oxford_temperatures.txt")

max_temp = np.array(dataset[:,2])
rain = np.array(dataset[:,5])

max_temp_train, max_temp_test, rain_train, rain_test = train_test_split(max_temp, rain, test_size=0.30, random_state=42)
max_temp_val, max_temp_test, rain_val, rain_test = train_test_split(max_temp_test, rain_test, test_size=0.50, random_state=42)

width_bin = 0.5
max_val = np.max(max_temp)
grid = np.arange(0, max_val + 1,width_bin)

# for a in np.arange(4, 25, 4):
#     split_and_plot(a, max_temp_train, rain_train, max_temp_val, rain_val)

In [76]:
print(max_temp_train.shape, rain_train.shape, max_temp_val.shape, rain_val.shape)

(1360,) (1360,) (292,) (292,)


In [77]:
max_temp_train_less_a = max_temp_train[max_temp_train<a]#.reshape(-1, 1)
max_temp_train_greater_a = max_temp_train[max_temp_train>=a]#.reshape(-1, 1)
max_temp_val_less_a = max_temp_val[max_temp_val<=a]#.reshape(-1, 1)
max_temp_val_greater_a = max_temp_val[max_temp_val>a]#.reshape(-1, 1)

In [88]:
max_temp_train_less_a = max_temp_train[np.where(max_temp_train < a)]
rain_train_less_a[np.where(max_temp_train < a)]
max_temp_train_greater_a = max_temp_train[np.where(max_temp_train >= a)]
rain_train_greater_a[np.where(max_temp_train >= a)]

(33,)

In [89]:
rain_train_less_a[np.where(max_temp_train_less_a <= a)].shape

(33,)

In [78]:
print(max_temp_train_less_a.shape, max_temp_greater_a.shape, max_temp_val_less_a.shape, max_temp_val_greater_a.shape)

(33,) (1328,) (3,) (289,)


In [79]:
np.sort(max_temp_train_less_a)

array([-0.2, -0.2,  0.2,  1. ,  1.6,  1.7,  1.7,  1.8,  1.8,  1.9,  2.7,
        2.7,  2.8,  3. ,  3.1,  3.2,  3.2,  3.2,  3.2,  3.3,  3.3,  3.5,
        3.5,  3.6,  3.7,  3.7,  3.7,  3.7,  3.8,  3.8,  3.9,  3.9,  4. ])

In [80]:
np.sort(max_temp_greater_a)

array([ 4. ,  4.1,  4.2, ..., 26.1, 26.4, 27.1])

In [64]:
s = np.sort(max_temp_train_less_a, axis=None)
s[:-1][s[1:] == s[:-1]]

array([-0.2,  1.7,  1.8,  2.7,  3.2,  3.2,  3.2,  3.3,  3.5,  3.7,  3.7,
        3.7,  3.8,  3.9])

In [65]:
s = np.sort(max_temp_greater_a, axis=None)
s[:-1][s[1:] == s[:-1]]

array([ 4.3,  4.3,  4.4, ..., 25.5, 25.8, 26.1])

In [47]:
rain_train_less_a = rain_train[:np.size(max_temp_train_less_a, 0)]
rain_train_greater_a = rain_train[np.size(max_temp_train_less_a, 0):]
rain_val_less_a = rain_val[:np.size(max_temp_val_less_a, 0)]
rain_val_greater_a = rain_val[np.size(max_temp_train_less_a, 0):]

In [58]:
rain_val_greater_a.shape

(259,)

In [48]:
max_temp_train_less_a = max_temp_train_less_a.reshape(-1, 1)
max_temp_train_greater_a = max_temp_train_greater_a.reshape(-1, 1)
max_temp_val_less_a = max_temp_val_less_a.reshape(-1, 1)
max_temp_val_greater_a = max_temp_val_greater_a.reshape(-1, 1)

In [49]:
a = 4

In [81]:
grid_less_a = grid[grid<=a]#.reshape(-1,1)
grid_greater_a = grid[grid>=a]#.reshape(-1,1)

In [82]:
grid_less_a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [84]:
grid_greater_a

array([ 4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,
        9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5,
       15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ,
       20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5,
       26. , 26.5, 27. , 27.5, 28. ])

In [53]:
reg = LinearRegression()

In [56]:
reg.fit(max_temp_train_greater_a[:-1], rain_train_greater_a)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [57]:
reg.predict(grid_less_a)

array([54.54011379, 54.57421048, 54.60830718, 54.64240387, 54.67650056,
       54.71059726, 54.74469395, 54.77879064, 54.81288734])

In [ ]:
reg.fit(max_temp_train_greater_a[:-1], rain_train_greater_a)