In [4]:
(100)**2 - (101)**2

-201

In [3]:
(100)**2

10000

In [5]:
101**2

10201

In [8]:
from math import sqrt

In [12]:
25 / (sqrt(400 * 100))

0.125

In [13]:
1/8

0.125

In [14]:
import numpy as np

In [19]:
x = [[100, 25, 0], [25,400,0], [0,0,0.16]]

In [20]:
x

[[100, 25, 0], [25, 400, 0], [0, 0, 0.16]]

In [35]:
Ux, Sx, Vx = np.linalg.svd(x, full_matrices=False)

In [36]:
Sx

array([4.02069063e+02, 9.79309367e+01, 1.60000000e-01])

In [37]:
Ux

array([[ 0.08248053,  0.99659268,  0.        ],
       [ 0.99659268, -0.08248053,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [40]:
np.matmul(x, Ux[:,0])

array([ 33.16287006, 400.6990837 ,   0.        ])

In [41]:
402 * Ux[:,0]

array([ 33.15717368, 400.63025576,   0.        ])

In [26]:
np.corrcoef(x, rowvar=False)

array([[ 1.        , -0.22332113, -0.69337525],
       [-0.22332113,  1.        , -0.54753313],
       [-0.69337525, -0.54753313,  1.        ]])

In [28]:
y = [[1, 0.125, 0], [0.125,1,0], [0,0,1]]

In [29]:
y

[[1, 0.125, 0], [0.125, 1, 0], [0, 0, 1]]

In [33]:
Uy, Sy, Vy = np.linalg.svd(y, full_matrices=False)

In [34]:
y_SVD = Uy @ np.diag(Sy) @ Vy
print("Is y close to y_SVD?", np.isclose(y, y_SVD).all())
print("Singular values:{}".format(Sy))

Is y close to y_SVD? True
Singular values:[1.125 1.    0.875]


In [42]:
Uy

array([[-0.70710678,  0.        , -0.70710678],
       [-0.70710678,  0.        ,  0.70710678],
       [ 0.        ,  1.        ,  0.        ]])

In [43]:
Sy

array([1.125, 1.   , 0.875])

In [44]:
np.linalg.eigh(x)

(array([1.60000000e-01, 9.79309367e+01, 4.02069063e+02]),
 array([[ 0.        , -0.99659268,  0.08248053],
        [ 0.        ,  0.08248053,  0.99659268],
        [ 1.        ,  0.        ,  0.        ]]))

In [45]:
np.linalg.eigh(y)

(array([0.875, 1.   , 1.125]), array([[-0.70710678,  0.        ,  0.70710678],
        [ 0.70710678,  0.        ,  0.70710678],
        [ 0.        ,  1.        ,  0.        ]]))